### ISSUE TITLE
SKnet101 Model

### ISSUE THREAD

**Issue by Alanzhang92** [implus/SKNet#1]
Excuse me, I found something wrong with SKnet101 Model.

The website it link to is https://github.com/implus/SKNet/blob/master, not like the other one is about drive.google.com

**Comment by cjnjuwhy** [comment]
Mark, and wait for the reply.

**Comment by implus** [comment]
Hi, the snapshot of sknet101 was deleted for saving disk spaces by mistake several days ago. I'm retraining a new model now, and it will be coming in 2-3 days. Thanks for waiting~
